line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "I", "N", "W", "UP", "B", "C4", "SIM"]
ignore = ["N818"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
