app:
  name: "jppt"
  version: "0.1.0"
  debug: false

logging:
  level: "INFO"
  format: "[{time:YYYY-MM-DD HH:mm:ss}][{level}]{message} [{file.name}:{line}]"
  rotation: "00:00"
  retention: "10 days"

telegram:
  enabled: false
  bot_token: ""
  chat_id: ""
